# Generated by Django 6.0.2 on 2026-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_std_sign_up_gender_std_sign_up_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='std_sign_up',
            options={'verbose_name': 'Student Sign Up', 'verbose_name_plural': 'Student Sign Ups'},
        ),
        migrations.AddField(
            model_name='std_sign_up',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='std_sign_up',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='std_sign_up',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='std_sign_up',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='std_sign_up',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='std_sign_up',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='std_sign_up',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
