# Generated by Django 6.0.2 on 2026-03-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_stdsignup_delete_std_sign_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdsignup',
            name='std_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='stdsignup',
            name='std_grade',
            field=models.CharField(max_length=30),
        ),
    ]
