# Generated by Django 6.0.2 on 2026-03-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_alter_stdsignup_std_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdsignup',
            name='id',
        ),
        migrations.AlterField(
            model_name='stdsignup',
            name='std_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
