# Generated by Django 6.0.2 on 2026-03-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_remove_stdsignup_id_alter_stdsignup_std_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdsignup',
            name='std_Id',
        ),
        migrations.AddField(
            model_name='stdsignup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stdsignup',
            name='std_password',
            field=models.CharField(max_length=20),
        ),
    ]
