# Generated by Django 6.0.2 on 2026-03-02 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_remove_stdsignup_std_id_stdsignup_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_father_name', models.CharField(max_length=100)),
                ('teacher_age', models.IntegerField()),
                ('teacher_qualification', models.CharField(max_length=50)),
                ('teacher_contact', models.CharField(max_length=15)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('teacher_password', models.CharField(max_length=20)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
