# Generated by Django 6.0.2 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_remove_stdsignup_user_remove_teachersignup_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersignup',
            name='teacher_major_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
