# Generated by Django 6.0.2 on 2026-03-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_rename_product_inventoryproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryProduct',
            new_name='ProductInventory',
        ),
    ]
