# Generated by Django 6.0.2 on 2026-03-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_rename_inventoryproduct_productinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='name',
            new_name='product_name',
        ),
    ]
