# Generated by Django 6.0.2 on 2026-03-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0005_rename_description_productinventory_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='price',
            new_name='product_price',
        ),
    ]
