# Generated by Django 6.0.3 on 2026-03-11 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0012_auto_populate_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='second_app__name_d9c611_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='product_discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='product_stock',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='second_app__product_423f04_idx'),
        ),
    ]
