# Generated by Django 6.0.2 on 2026-02-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_blogpost_author_remove_blogpost_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_sign_up',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10),
        ),
        migrations.AddField(
            model_name='std_sign_up',
            name='grade',
            field=models.CharField(default='Not Assigned', max_length=10),
        ),
    ]
