# Generated by Django 6.0.2 on 2026-02-28 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_alter_std_sign_up_options_std_sign_up_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='std_sign_up',
            name='auth_user',
        ),
        migrations.AddField(
            model_name='std_sign_up',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
