# Generated by Django 6.0.2 on 2026-02-28 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_remove_std_sign_up_auth_user_std_sign_up_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StdSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=100)),
                ('std_father_name', models.CharField(max_length=100)),
                ('std_age', models.IntegerField()),
                ('std_gender', models.CharField(max_length=10)),
                ('std_grade', models.CharField(max_length=10)),
                ('std_contact', models.CharField(max_length=15)),
                ('std_email', models.EmailField(max_length=254, unique=True)),
                ('std_password', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='std_sign_up',
        ),
    ]
