# Generated by Django 6.0.2 on 2026-03-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_alter_stdsignup_std_email_alter_stdsignup_std_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdsignup',
            name='std_Id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
