# Generated by Django 6.0.2 on 2026-03-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_alter_stdsignup_std_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdsignup',
            name='std_Id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
