# Generated by Django 6.0.2 on 2026-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_teachersignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersignup',
            old_name='teacher_age',
            new_name='teacher_cnic',
        ),
        migrations.AddField(
            model_name='teachersignup',
            name='teacher_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
