# Generated by Django 6.0.2 on 2026-03-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
