# Generated by Django 6.0.2 on 2026-03-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='InventoryProduct',
        ),
    ]
