# Generated by Django 6.0.2 on 2026-03-10 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0008_product_productimage_productspecification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='second_app__product_423f04_idx',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_stock',
            new_name='stock',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='second_app__name_d9c611_idx'),
        ),
    ]
